### ISSUE TITLE
Failed to execute the process make

### ISSUE THREAD

**Issue by j1012** [azubieta/KDE-AppImage-Thumbnailer#6]
Error:
`[  5%] Performing download step (git clone) for 'AppImageKit'
Cloning into 'AppImageKit'...
fatal: invalid reference: appimagetool/master
CMake Error at /home/juninho/Downloads/KDE-AppImage-Thumbnailer-2.0/build/AppImageKit-prefix/tmp/AppImageKit-gitclone.cmake:75 (message):
  Failed to checkout tag: 'appimagetool/master'

CMakeFiles/AppImageKit.dir/build.make:89: recipe for target 'AppImageKit-prefix/src/AppImageKit-stamp/AppImageKit-download' failed
make[2]: *** [AppImageKit-prefix/src/AppImageKit-stamp/AppImageKit-download] Error 1
CMakeFiles/Makefile2:99: recipe for target 'CMakeFiles/AppImageKit.dir/all' failed
make[1]: *** [CMakeFiles/AppImageKit.dir/all] Error 2
Makefile:140: recipe for target 'all' failed
make: *** [all] Error 2
`

**Comment by azubieta** [comment]
Hello @jcmljunior thanks for looking at this project. The error seems to be produced by changes in the thirdparty repositories that this project depends on. I would have to do some patches in order to make this work.

But I also started another project that provides the thumbnails feature and others. I guess that it would be better to try that one. The url is: https://www.opencode.net/azubieta/plasma-appimage-integration/ you can also find some binaries ready at: https://www.pling.com/p/1314868/

If you have any issues with that project please fell free to open an issue or ping me on the #appimage channel at freenode.net

I guess I'll set this project as archived.

**Comment by azubieta** [comment]
This feature would be better supported at https://www.opencode.net/azubieta/plasma-appimage-integration/

Closing issue in order to archive the project.
